### ISSUE TITLE
add treehouses remote services status

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/cli#1013]
A command to return all of the services' status (including running, installed, available, icon, info, autorun data).
If it is possible, perhaps the best way would be in JSON format as a string or perhaps each section of the string is labeled with a unique identifier to separate sections/ services.

**Comment by kjong** [comment]
```
{
  "available":["couchdb", "kolibri", "mariadb", "mastodon"],
  "installed":["couchdb", "kolibri", "mastodon"],
  "running":["couchdb", "mastodon"],
  "icon":{
      "couchdb":"<svg>",
      "kolibri":"<svg>",
      "mariadb":"<svg>",
      "mastodon":"<svg>"
   }
  "info":{
      "couchdb":"<info>",
      "kolibri":"<info>",
      "mariadb":"<info>",
      "mastodon":"<info>"
   }
  "autorun":{
      "couchdb":"true/false",
      "kolibri":"true/false",
      "mariadb":"true/false",
      "mastodon":"true/false"
   }
}
```

Would a json like this work?

**Comment by sriharivishnu** [comment]
The JSON object itself as a string worked, however, the second code string (one-liner) did not. One mistake I found was the `\/` character, which was not recognized.

**Comment by kjong** [comment]
I'm assuming there's some character in there that needs to be escaped. Once I have the final output I'll show it to you so that we can check again.

**Comment by sriharivishnu** [comment]
Ok thanks!
