### ISSUE TITLE
treehouses rtc

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#104]
`treehouses rtc off`
`treehouses rtc <rtcchip>`

https://github.com/treehouses/builder/blob/master/examples/bell_RTC_autorunonce#L53

right now supported rtcchips:
- "rasclock" or ds1307
- ds3231

**Comment by rhuturajm** [comment]
To be on same page, a cli command has to be created to turn rtc off as well as another command to display rtc chip used by rpi?

**Comment by i5o** [comment]
@rhuturajm this command basically adds or remove stuff from /boot/config
see: https://github.com/treehouses/builder/blob/master/examples/bell_RTC_autorunonce#L53
