### ISSUE TITLE
power scaling

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#1052]
https://i.ytimg.com/vi/f2CMTkXf3sE/maxresdefault.jpg
e.g. Other modes online available
```
echo "powersave"| sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
```

**Comment by law-lin** [comment]
More info at https://www.raspberrypi.org/forums/viewtopic.php?t=152692
Possible commands to use are:
-  `treehouses cpu [mode]`
- `treehouses power [mode]`

5 modes are: 
1. ondemand : default, moves speed from min to max and back at a % of load
2. conservative : gradually switch frequencies at % of load
3. userspace : use user specified frequencies
4. powersave : all cores set at minimum frequency
5. performance : all cores set at maximum frequency
