### ISSUE TITLE
can we detect if there is a camera plugged in

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#1315]

**Comment by LordJashin32** [comment]
```bash
v4l2-ctl --list-device
root@treehouses:/home/pi/Videos# v4l2-ctl --list-devices
bcm2835-codec-decode (platform:bcm2835-codec):
	/dev/video10
	/dev/video11
	/dev/video12

mmal service 16.1 (platform:bcm2835-v4l2):
	/dev/video0

root@treehouses:/home/pi/Videos#
```

Camera Version | Max (microseconds)
-- | --
V1 (OV5647) | 6000000 (i.e. 6s)
V2 (IMX219) | 10000000 (i.e. 10s)
HQ (IMX477) | 200000000 (i.e. 200s)

**Comment by LordJashin32** [comment]
If we want to detect which camera version looks like we will have to check max resolutions. And if we want to detect if camera is connected or not we just have to try and take a picture and if it returns the right error message then there's no camera still connected.

**Comment by LordJashin32** [comment]
We can use the values here https://www.raspberrypi.org/documentation/hardware/camera/
