### ISSUE TITLE
`treehouses magazine` no Internet found error

### ISSUE THREAD

**Issue by law-lin** [treehouses/cli#1407]
None of the commands work, but I am clearly connected to WiFi.
```
root@treehouses:~/cli# treehouses magazine
Error: no Internet found
root@treehouses:~/cli# treehouses detect wifi
true
root@treehouses:~/cli# treehouses magazine
Error: no Internet found
root@treehouses:~/cli# treehouses magazine magpi
Error: no Internet found
root@treehouses:~/cli# treehouses networkmode
wifi
root@treehouses:~/cli# treehouses networkmode info
essid: NETGEAR75, ip: 192.168.1.20, has password



```

**Comment by jayala-29** [comment]
not sure why this is happening, hopefully it's fixed with the updated `treehouses magazine` y'all have been improving :)

**Comment by kjong** [comment]
I'm not able to reproduce this issue.

@law-lin Can you try running `treehouses internet`?

**Comment by law-lin** [comment]
Closing this as it seems to work now. `treehouses internet` returned true as well at the time. I made no changes whatsoever though. Maybe my RPi couldn't communicate with https://magpi.raspberrypi.org/issues at the time?
