### ISSUE TITLE
treehouses bridge causes hotspot and bluetooth

### ISSUE THREAD

**Issue by leomaxi** [treehouses/cli#151]
After making a bridge by updating the autorunonce file. The hotspot doesn't appear to be connected for long minutes. When it appears for connection, bluetooth becomes finicky. Android devices cant connect to the raspberry pi via bluetooth from OS and from treehouses remote app.

**Comment by i5o** [comment]
@leomaxi can you paste the autorun file here?

**Comment by i5o** [comment]
```bash
#!/bin/bash
treehouses bluetooth on
treehouses bridge Chocolate MyRaspi fosforito ignaciorocks
```
