### ISSUE TITLE
I do not think we should be sending stdout and stderr to /dev/null

### ISSUE THREAD

**Issue by sente** [treehouses/cli#169]
If something is broken we'd never know

https://github.com/treehouses/cli/blob/d6b49c656111b3e5c44d031e04832c318425dfc0/modules/globals.sh#L14-L17

**Comment by shubhambhattar** [comment]
@sente Can you tell me where you want this to be redirected (to which path)? I would like to work on it.

**Comment by LordJashin32** [comment]
mm. This is important. We have a lot of code pointing to the void (dev/null). Will have to change that and run checks to see if there is any existing errors in the wild.
