### ISSUE TITLE
`treehouses internet` not working

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/cli#1791]
Tried the following to test the command:
- Switched to a wifi that does not exist (`treehouses wifi kasdjflaf kdfjlafd`)
- Tried `treehouses internet`, and got an output of "true"

**Comment by dogi** [comment]
`if nc -w 10 -z 8.8.8.5 53; then echo "true"; else echo "false"; fi`

**Comment by dogi** [comment]
iproute is caching which is a problem
