### ISSUE TITLE
`treehouses services <service> config edit` error

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/cli#1816]
When using over the phone, it tries to kill a spinner that does not exist
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
 S - tput: No value for $TERM and no -T specified

**Comment by dogi** [comment]
https://github.com/treehouses/cli/blob/master/modules/services.sh#L415
is the cause for it ...

... over the phone no spinner is working so just terminating a non started spinner is destined to fail
