### ISSUE TITLE
change base ip on treehouses ap

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#187]
192.168.2.x to some other base ip

**Comment by empeje** [comment]
what is the form of the cli command do you prefer @dogi?

```
treehouses ap local apName apPassword 129.168.2
```

something like that?

**Comment by dogi** [comment]
`treehouses ap local|internet <essid> [password] [-ip x.y.z.0]`

**Comment by dogi** [comment]
So fat netmask will be just fixed .... `255.255.255.0`
