### ISSUE TITLE
treehouses detect network mode for remote app

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#211]

**Comment by Sriharsha-Singam** [comment]
![6668425139481430958](https://user-images.githubusercontent.com/14966231/50378371-d97a1700-05fe-11e9-8171-921d855c469c.png)

Treehouse App Network Page

**Comment by dogi** [comment]
@Sriharsha-Singam  thanks

basically we would to show active mode also in treehouses/remote app

**Comment by i5o** [comment]
we already have networkmode, so am I missing something? @dogi

**Comment by i5o** [comment]
https://github.com/treehouses/cli/blob/master/modules/networkmode.sh#L11

**Comment by dogi** [comment]
@i5o yes you are right - but think we need all ipv4 numbers we know not just the mode
