### ISSUE TITLE
treehouses services to support remote app

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#213]
![0 6 7-12](https://user-images.githubusercontent.com/13684059/50378659-86579280-0605-11e9-8b4a-8a4d8dc6c777.png)

**Comment by i5o** [comment]
wondering how this would work?

the issues you assigned shouldn't take much time -- but clarification is needed

**Comment by dogi** [comment]
`treehouses services all` to list all the potential services

**Comment by dogi** [comment]
`docker images | grep $service_name`
