### ISSUE TITLE
treehouses torify

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#228]

**Comment by i5o** [comment]
possible commands:


treehouses tor => lists the hostname
treehouses tor list => lists the shared ports
treehouses tor add [localPort] [externalPort] => add shared ports
treehouses tor stop => stops the server
treehouses tor destroy => brings back the original config and stops the server
treehouses tor start => starts the server

adds a line to /etc/tor/torrc

tor service must be restarted after that

HiddenServiceDir /var/lib/tor/hidden_service/
HiddenServicePort 80 127.0.0.1:80
HiddenServicePort 22 127.0.0.1:22


to get address

root@treehouses:/home/pi# cat /var/lib/tor/hidden_service/hostname
hi566cwkavutwqc3wg4uxsqqzesqbd7dn5ilxaeulg7l25hhvw67mdad.onion
root@treehouses:/home/pi#
