### ISSUE TITLE
add badges README.md

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#339]
https://shields.io/category/downloads

`/npm/:interval/:scope?/:packageName.svg`

**Comment by dogi** [comment]
https://shields.io/category/version

**Comment by ArranHL** [comment]
Is it the ![image](https://user-images.githubusercontent.com/47016295/61976234-e9723300-aff3-11e9-95b8-0cc30486ad80.png) we want?

**Comment by dogi** [comment]
@ArranHL yes
