### ISSUE TITLE
is treehouses feedback breaking when used without quotes?

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#373]

**Comment by hiroTochigi** [comment]
@dogi please explain more.

**Comment by dogi** [comment]
test how to break `treehouses feedback <feedback>`
<feedback> is taken on as `$@` and I think there is a way to break the command when not in quote or double quote

**Comment by LordJashin32** [comment]
This works with or without quotes. Seeing as this issue has been solved. Closing.
