### ISSUE TITLE
How to connect to WPA2/PEAP/MSCHAPv2 enterprise wifi networks

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/cli#431]
Need to find a proper solution to  connect rp4 to enterprise wifi networks.
FYI:
> in ubuntu base, This following article mentions where they contain for the rp4  [How to connect to WPA2/PEAP/MSCHAPv2 enterprise wifi networks](https://askubuntu.com/questions/279762/how-to-connect-to-wpa2-peap-mschapv2-enterprise-wifi-networks-that-dont-use-a-c#295600).
> This [network manager](https://raspberrypi.stackexchange.com/questions/29783/how-to-setup-network-manager-on-raspbian) utility support WPA2/PEAP/MSCHAPv2 enterprise wifi networks.

**Comment by dogi** [comment]
https://gist.github.com/elec3647/1e223c02ef2a9a3f836db7984011b53b

**Comment by dogi** [comment]
old https://www.raspberrypi.org/forums/viewtopic.php?t=111100

**Comment by dogi** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=44029

**Comment by LordJashin32** [comment]
https://github.com/CompEng0001/RaspberryPiEnterpriseSetup/blob/master/wpa_enterprise.sh
