### ISSUE TITLE
ending prompt for treehouses clone

### ISSUE THREAD

**Issue by CalebProvost** [treehouses/cli#435]
When `treehouses clone /dev/sda` is finished, it should prompt the user that a reboot is necessary and ask if they would like to do so now.

**Comment by vmnet8** [comment]
Yes, agree with you. 
Actually, I think it needs to force the OS to reboot, otherwise a read -only OS almost can do nothing.

**Comment by CalebProvost** [comment]
hm... I wonder what @dogi thinks.
