### ISSUE TITLE
treehouses discover?

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#448]
.... using `nmap`

**Comment by xavierh93** [comment]
@dogi what exactly do you want this discover command to do?

**Comment by dogi** [comment]
@xavierh93 use `nmap` to discover stuff on the networks

- more pi's ... all MAC address start with `b8:27:eb`
- ...?

**Comment by xavierh93** [comment]
https://udger.com/resources/mac-address-vendor-detail?name=raspberry_pi_foundation

**Comment by xavierh93** [comment]
DC:A6:32
