### ISSUE TITLE
treehouses led dance: different output remote vs cli

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/cli#534]
# treehouses led
`treehouses led dance`, `treehouses led thanksgiving` and `treehouses led christmas` produce an error while running from remote, however, no error on cli is produced.

<img width="439" alt="Screen Shot 2019-12-04 at 10 24 32 PM" src="https://user-images.githubusercontent.com/37857112/70201587-15f63400-16e5-11ea-931d-dd89b9545aae.png">

**Comment by pattanawadee88** [comment]
<img width="383" alt="Screen Shot 2019-12-06 at 9 34 05 PM" src="https://user-images.githubusercontent.com/52762574/70367680-3272a780-1870-11ea-9d1c-2a994b127aa3.png">

it is working fine for me
