### ISSUE TITLE
treehouses led : Regression? from version 1.10.6 to 1.10.7

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/cli#536]
Top two commands are version 1.10.6 when trying to run `treehouses led dance`
The bottom two commands are version 1.10.7

<img width="437" alt="Screen Shot 2019-12-11 at 7 21 19 PM" src="https://user-images.githubusercontent.com/37857112/70671853-73413680-1c4b-11ea-8c4d-e1c3fc7dec13.png">

Looking at the file history, perhaps something to do with the addition of led both?

**Comment by dogi** [comment]
@pattanawadee88 please revert it by removing all `treehouses led both` we introduced
