### ISSUE TITLE
treehouses memory has no output

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#547]
... when done in the terminal in treehouses remote

**Comment by dogi** [comment]
![image](https://user-images.githubusercontent.com/13684059/71301850-67075880-2372-11ea-8eae-dd985777afe1.png)

**Comment by dogi** [comment]
```
root@treehouses:~# treehouses memory
Your rpi has 946664 bytes of total memory with 745680 bytes used and 200004 bytes available
```

release-115 and remote 1830

**Comment by sriharivishnu** [comment]
It was working for me:
<img width="434" alt="Screen Shot 2019-12-20 at 9 57 54 PM" src="https://user-images.githubusercontent.com/37857112/71301963-d3cf2280-2373-11ea-8e46-05b86e4e3544.png">

release-111 and remote 1830

**Comment by dun08015** [comment]
![Screenshot_20191220-185503](https://user-images.githubusercontent.com/3333070/71303258-5ea32380-235a-11ea-8b20-f5bb5bb09fb1.png)
release-114 remote 1830

**Comment by Nida8930** [comment]
![Screenshot_20191221-002612](https://user-images.githubusercontent.com/49969541/71304180-a2148680-2388-11ea-8016-59fa34809e85.png)
Everything appears to be working for me. Treehouses 115, remote 1830, 3B+.
