### ISSUE TITLE
add CHANGELOG.md

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/cli#559]
Generate a record so that people can track bugs and upcoming features. This log should reflect the current features of the latest images. The downside is that we must have the members to monitor this file, making sure features are deliverable.

**Comment by LordJashin32** [comment]
This sounds sort of ambiguous. If there is a bug that can't be squashed there should still be an issue open for it. Isn't github like a bug tracker at this point? If there is bugs that aren't on the issues page than yes I personally would like a list of them in a file somewhere. Features i think is covered by the help command. 

This changelog idea is great for customers/consumers. Idk but maybe make a change log here and then somewhere in planet or somewhere else they can pull it up?

**Comment by dogi** [comment]
we add changelog automatically when putting it into https://npmjs.org
