### ISSUE TITLE
fahrenheit temp calc off

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#561]
37 celsius on google calculates to 98.6 Fahrenheit. But on our command it comes out to 100+ fahrenheit.
when running treehouses temperature fahrenheit

**Comment by dun08015** [comment]
I think it may be an issue of temperature fluctuation. I noticed when I was testing that it would sometimes not match what google said but then when I tried again they would match.

To be sure, I made a branch "both_temps" in which I edited temperatures.sh with a new command "temperature both" to print both temps at the same time.

It does look like there is an issue with the program rounding down the decimals when it should round up. I can take a look at that later. Or if anyone else wants to look into it, I don't mind.

Here are some results:
![temperatureCheck](https://user-images.githubusercontent.com/3333070/71651533-77003000-2cc2-11ea-81d7-0a0fb66715fc.PNG)
