### ISSUE TITLE
combine wifi wifihidden

### ISSUE THREAD

**Issue by Nida8930** [treehouses/cli#574]
## Proposal

After working with the wifi, hidden wifi, and wifistatus commands I think that the code could be tidied up by combining these three closely related features into one command. Allowing users to run things like 
    
    `treehouses wifi status`
    `treehouses wifi mywifi mypassword`
    `treehouses wifi mywifi mypassword hidden`

rather than having three separate modules for each individual task.

**Comment by Neethu-Mohan** [comment]
https://github.com/treehouses/cli/commit/5b27b5128d72360089f7e75301362f50c1566af6
like above I will create for "wifi" and "wifi main function"
