### ISSUE TITLE
test treehouses bridge

### ISSUE THREAD

**Issue by i5o** [treehouses/cli#60]

**Comment by i5o** [comment]
Rpi Zero W
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword** **HostpotPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **""** **HotspotPassword**_

**Comment by i5o** [comment]
Rpi Zero W USB
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword** **HostpotPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **""** **HotspotPassword**_

**Comment by i5o** [comment]
Rpi Zero 3B
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword** **HostpotPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **""** **HotspotPassword**_

**Comment by i5o** [comment]
Rpi Zero 3B+
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword** **HostpotPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **""** **HotspotPassword**_

**Comment by i5o** [comment]
Rpi 3B+
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword** **HostpotPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **""** **HotspotPassword**_

**Comment by i5o** [comment]
Rpi 3B+ eth0
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword** **HostpotPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **NetworkPassword**_
- [ ] treehouses bridge _**NetworkName** **HostpotName**_
- [ ] treehouses bridge _**NetworkName** **HostpotName** **""** **HotspotPassword**_

**Comment by i5o** [comment]
**_testing rpi3b+ notes_**
```
sudo treehouses upgrade
sudo raspi-config  # set wifi country to 'US' (4, 4, us)
sudo treehouses bridge IgnacioGuest 3bplusrpi
sudo reboot
```

**Comment by xyb994** [comment]
Looks like Rpi Zero W usb0 all works, have to wait a little longer before and after reboot...
