### ISSUE TITLE
treehouses services <service> url(s)?

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#606]

**Comment by jamjakpa** [comment]
treehouses services <nextcloud>  http://10.1.10.102:8081/  working 
![image](https://user-images.githubusercontent.com/44546990/72687225-9c59b000-3ab0-11ea-8606-f3dbbc0eafab.png)
![image](https://user-images.githubusercontent.com/44546990/72687232-ba271500-3ab0-11ea-9436-081b3ca59ade.png)
