### ISSUE TITLE
Feature for checking network usage or devices connected to hotspot

### ISSUE THREAD

**Issue by lmmrssa** [treehouses/cli#618]
As we have limit of devices that connect to rpi. It will be nice to see how many devices are connected right now and how much traffic they are using.

**Comment by dogi** [comment]
`treehouses discover` function?

we could look into dhcp leases
but there must be also something elso

**Comment by LordJashin32** [comment]
```iftop``` seems like the best live implementation for this for the terminal. ```Vnstat/vnstati``` perhaps for longer term data to look at.
