### ISSUE TITLE
change to not executable

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#630]
![image](https://user-images.githubusercontent.com/13684059/73133382-ed5c2d80-3ff5-11ea-80ef-049d4b84f942.png)

`camera.sh` and `reboots.sh`

**Comment by jamjakpa** [comment]
> ![image](https://user-images.githubusercontent.com/13684059/73133382-ed5c2d80-3ff5-11ea-80ef-049d4b84f942.png)
> 
> `camera.sh` and `reboots.sh`

hi @dogi, 
don't i need owner right before i can do it ) directory right , etc to to make it not executable
