### ISSUE TITLE
find vendor code of rpi

### ISSUE THREAD

**Issue by phamduchongan93** [treehouses/cli#643]
- Used to find the hardware code from the vendor.
```
pi@treehouses:~ $ cat /proc/cpuinfo  | grep Revision
Revision        : b03111
```

- Proposed format:
```
Usage: treehouses revision"
```

**Comment by kjong** [comment]
I'm not sure how useful this would be given that we already have `detectrpi`.

If we wanted a `treehouses revision` command, we would need to run `checkrpi` first which ends up calling `detectrpi` anyways.

Maybe we could add this functionality to `detectrpi`? So something like `treehouses detectrpi revision`?

**Comment by phamduchongan93** [comment]
@kjong right. Let's group them up.
