### ISSUE TITLE
services: wrong ip address url

### ISSUE THREAD

**Issue by sriharivishnu** [treehouses/cli#649]
```
root@sriharivishnu:~# treehouses services planet url both
169.254.4.234:80
169.254.4.234:2200 
...
```

**Comment by kjong** [comment]
Will probably switch to using `ifconfig` instead of `hostname -I` to get the ip address.

**Comment by vmnet8** [comment]
under release-121, it works well for me. both local and tor address are correct.
is it not a common problem?

**Comment by kjong** [comment]
It wasn't a problem for everyone.

Basically, I was using `hostname -I` and taking the first result to get the ip address but the first result wasn't always the correct ip address.

So it would work for some but not for others.

The change to using `networkmode info` should produce more consistent results.
