### ISSUE TITLE
treehouses tor ports?

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#655]
cause in https://github.com/treehouses/cli/pull/654
we wanna exchange bad https://github.com/treehouses/cli/blob/68280015e6f52d449d225cf32802f0db85dcc000/templates/network/tor_report.sh#L4 with `$(treehouses tor ports)`

**Comment by jamjakpa** [comment]
```
treehouses tor list | sed '1d' | sed "s/  <=> /:/g" | tr "\n" " " | sed 's/.$//'
```
