### ISSUE TITLE
services.sh direct execution rather than calling bash

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#668]
Right now we are using bash to execute scripts when we could just make the script executable, add a shebang (which it probably already has) and just execute directly. 
```bash $TEMPLATES/services/portainer/portainer_yml.sh```
->
```.$TEMPLATES/services/portainer/portainer_yml.sh```

**Comment by kjong** [comment]
Removing the shebang from some scripts (per #666) and keeping them in others makes things very inconsistent and removes a lot of flexibility with regards to how we use the scripts (both executing directly and calling them in other scripts).

I'd rather have the shebang and not need it, than need it and not have it.

Anyways, as I mentioned in #666, we need the shebangs to ensure that the correct interpreter is used.

**Comment by LordJashin32** [comment]
> Removing the shebang from some scripts (per #666) and keeping them in others makes things very inconsistent and removes a lot of flexibility with regards to how we use the scripts (both executing directly and calling them in other scripts).
> 
> I'd rather have the shebang and not need it, than need it and not have it.
> 
> Anyways, as I mentioned in #666, we need the shebangs to ensure that the correct interpreter is used.

Wouldn't be removing the shebang this time. It would be instead of doing ```bash ./yml_create.sh```
we would do ```./yml_create.sh``` and just call it directly.

**Comment by LordJashin32** [comment]
Just gonna close this my idea didn't work out. Owell. Better luck next time.
