### ISSUE TITLE
treehouses wificountry?

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#676]
```
$ treehouses wificountry
Success: the wifi country has been set to
```

is doing strange stuff
it should show which country it is set too

**Comment by dogi** [comment]
is `treehouses default network` resetting wificountry?

**Comment by jamjakpa** [comment]
i get on my pi Image version release-120 

![image](https://user-images.githubusercontent.com/44546990/74298439-a319c280-4cfe-11ea-9c5d-3b190671aaf6.png)

**Comment by Nida8930** [comment]
@jamjakpa this is an issue we have been having on the experimental image release [here](http://download.treehouses.io/experiment/treehouse-raspbiantwenty0.img.gz).

@dogi on the Rpi3B+ it says the wifi is unable to connect until wifi country is set using raspi-config. Raspi-config does not work until you run `treehouses default network` and reboot. After this you are able to set the wifi country using raspi-config and then use `treehouses wifi` as normal.

`treehouses default network` does reset the wifi country as far as I know, unless it is set somewhere besides wpa_supplicant.conf. Once the wifi country is initially set by raspi-config everything still works even if it is reset later by `default network`.

As far as the wificountry function goes, it sets the wifi country only. so `treehouses wificountry` with no argument should return an error or more needs to be modified to return what the current wifi country is set to if no argument is given. 

`treehouses wificountry <country>` appears to work as it should.
