### ISSUE TITLE
treehouses detectrpi outdated

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#722]
From the raspberrypi website:

> Why does cpuinfo report I have a BCM2835?
 The upstream Linux kernel developers had decided that all models of Raspberry Pi return bcm2835 as the SoC name. At Raspberry Pi we like to use as much upstream kernel code as possible, as it makes software maintenance much easier, so we use this code. Unfortunately it means that cat /proc/cpuinfo is inaccurate for the Raspberry Pi 2, Raspberry Pi 3 and Raspberry Pi 4, which use the bcm2836/bcm2837, bcm2837 and bcm2711 respectively. You can use cat /proc/device-tree/model to get an accurate description of the SoC on your Raspberry Pi model.

So we should be using ```/proc/device-tree/model``` instead of ```/proc/cpuinfo``` where possible.

**Comment by dogi** [comment]
https://www.cnx-software.com/2020/02/24/raspberry-pi-4-rev-1-2-fixes-usb-c-power-issues-improves-sd-card-resilience/

**Comment by dogi** [comment]
`cat /sys/firmware/devicetree/base/model`
