### ISSUE TITLE
functions using exit 0 for error?

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#724]
I think this is ambiguous from a user perspective. If someone uses the output of cli.sh into their own script it would be giving an okay exit status for something that failed to run. Exit 0 should be if the thing executed all the way thru everything without hitting an if statement. Is there some convention here I am not getting?
```
  #check if device has wifi
      if iwconfig wlan0 2>&1 | grep -q "No such device"; then
        echo "Error: no wifi device is present"
        exit 0
      fi
```

**Comment by kjong** [comment]
They should probably be `exit 1`s.
