### ISSUE TITLE
treehouses bluetooth and bluetoothid revamp needed

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#748]
- Why not one file for all bluetooth functionality?
- ~Code in bluetooth.sh seems to be broke ```treehouses bluetooth id```~
- Why are case statements and if statements for status mixed together?
- The files bluetooth.sh and bluetoothid.sh seem pretty small seems to be an easy refactor here
- No need for bluetoothid file. Suggested for removal

-  [ ] Deprecate bluetoothid.sh
-  [ ] Revamp bluetooth.sh

**Comment by dogi** [comment]
https://github.com/treehouses/cli/search?q=bluetoothid&unscoped_q=bluetoothid

**Comment by dogi** [comment]
check already @Neethu-Mohan `treehouses bluetoothid` is not used in any other repositories anymore
