### ISSUE TITLE
way to generate _treehouses semi-automatic

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#826]
... or for now just complete it up to level 3+

**Comment by LordJashin32** [comment]
We could parse help in order to create it. Maybe with one make a command list for remote. And the other generate the _treehouses file. This is the only way outside of creating an entirely separate file that we have to update with the list of commands.

**Comment by LordJashin32** [comment]
I don't think we need this anymore. The _treehouses is pretty automatic now. Closing this issue.
