### ISSUE TITLE
`treehouses services autorun` sends false true

### ISSUE THREAD

**Issue by hiroTochigi** [treehouses/cli#901]
```
root@raspberrypi:~/cli# treehouses services privatebin autorun
true
root@raspberrypi:~/cli# treehouses services privatebin up
/srv/privatebin/privatebin.yml not found
try running 'treehouses services privatebin install' first
```

This happens after `treehouses services [service name] autorun true` and `treehouses services [service name] down`, and `treehouses services [service name] cleanup`.

**Comment by kjong** [comment]
If I'm understanding the issue correctly, after setting `autorun true` and doing `cleanup`, autorun is still set to true?

Then the solution would be to run `treehouses services <service> autorun false` when doing `cleanup`.
