### ISSUE TITLE
treehouses help ap & aphidden need noob friendly

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#907]
Right now it doesn't tell non network savy users what to do to make this work on their phone or anything. Setting IP address to static and setting the gateway and ip address isn't automatic in some1's head unless they know what they are doing. Recommend for change.

**Comment by kjong** [comment]
Should this issue be closed?

**Comment by LordJashin32** [comment]
> Should this issue be closed?

I guess. I still don't know why DHCP doesn't work with my phone. But whatever. Closing.
