### ISSUE TITLE
treehouses globals & treehouses config commands break cli

### ISSUE THREAD

**Issue by LordJashin32** [treehouses/cli#926]
```bash
root@raspberrypi:~/cli# ./cli.sh globals sdfsd
./cli.sh: line 18: globals: command not found
root@raspberrypi:~/cli# ./cli.sh config dfds
./cli.sh: line 18: config: command not found
root@raspberrypi:~/cli#
```

**Comment by kjong** [comment]
I would assume this is because `globals.sh` doesn't have a `function globals {}`.
Same for `config.sh`.

**Comment by LordJashin32** [comment]
> I would assume this is because `globals.sh` doesn't have a `function globals {}`.
> Same for `config.sh`.

Correct. Gonna assign myself to this one.
