### ISSUE TITLE
treehouses services environment variables

### ISSUE THREAD

**Issue by kjong** [treehouses/cli#942]
Configuring environment variables for services
`treehouses services <service> environment`

### services.sh
```
if [ $(source $SERVICES/install-${service_name}.sh && uses_env) = true ]; then
  if [ -e /srv/$service_name/.env ]; then
    vim /srv/$service_name/.env
  else
    echo "ERROR: /srv/$service_name/.env not found"
    echo "try running '$BASENAME services $service_name install' first"
    exit 1
  fi
else
  echo "$service_name does not take environment variables"
fi
```

### /srv/$service_name/.env
```
  NAME_VAR=name
  ...
```
If using .env files that are placed in /srv/<service>, need to run docker-compose with `--project-directory` eg. `docker-compose --project-directory /srv/seafile -f /srv/seafile/seafile.yml config`

### /srv/$service_name/$service_name.yml
```
  environment:
    - NAME=${NAME_VAR}
    ...
```

### /services/install-${service_name}.sh
```
function uses_env {
  return true / false
}
```
Instead of `uses_env`, just search inside `install` for a .env file being created?
This approach will require a `function uses_env` inside services.sh.
```
function install {
  # create .env
  {
    echo "NAME_VAR="
  } > /srv/$service_name/.env
```

### Potential Issues
* What happens if .env has empty environment variables (eg. `- NAME=`) when doing `up`?
~It looks like docker just goes ahead and leaves that variable empty / blank.~
~How do we prevent this?~
Docker-compose throws a warning (not an error) that should be able to be caught.
Can `grep` for these warnings.
```
root@kjong:~/cli# docker-compose -f /srv/seafile/seafile.yml config
WARNING: The SEAFILE_ADMIN_VAR variable is not set. Defaulting to a blank string.
WARNING: The SEAFILE_ADMIN_PW_VAR variable is not set. Defaulting to a blank string.
```
Create a `validate_yml` function that runs `docker-compose config` and checks for warnings.

* Need to ensure that .env file is properly configured before trying to create the container.
One way to do this would be to automatically call `treehouses services <service> environment` inside `install` so that when users `install` a service, they are also prompted to edit the .env file at the same time.

* Possible to edit .env files using vim via Remote?

* Use `docker-compose -f <service.yml> config` to look at .yml configured with .env variables?

* Add .envs to .gitignore

* Multiple .env files (if secondary .env values are blank = use default values from primary .env)
We can use `env_file` inside the docker-compose yml to specify a env file to use (makes it easier to pick between multiple env files)

* How to recreate container with updated env variables?
Run `docker-compose build` to rebuild

* Force user to edit .env everytime they run install or up?

**Comment by LordJashin32** [comment]
Need to also be careful of variable name conflicts between services. If they both use the same variable name we could run into trouble. I assume these would be global variables. Anyway. Its a cool idea.

**Comment by kjong** [comment]
I was thinking of using separate environment files for each service. While it would be "easier" to use a single file, it would not be very fun trying to make sure there are no variable conflicts like you said.

Still fleshing out this feature so more suggestions are welcome.
