### ISSUE TITLE
put command in order

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#96]
what is the ideal order of our commands?

**Comment by dogi** [comment]
help
expandfs
rename
password
sshkeyadd
version
detectrpi
ethernet
wifi
staticwifi
bridge
container
bluetooth
hotspot
timezone
locale
ssh
vnc
default 
upgrade

**Comment by rhuturajm** [comment]
help
detectrpi
rename
password
timezone
ethernet
bluetooth
wifi
staticwifi
hotspot
bridge
ssh
sshkeyadd
vnc
version
expandfs
locale
container
upgrade
default
